### ISSUE TITLE
Incorrect error message for complex commands

### ISSUE THREAD

**Issue by Gavino3o** [AY2324S1-CS2103T-W13-1/tp#171]
![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/95404279/3d685a48-53b8-4008-af97-6e6638ad73b7)

![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/95404279/16cb820f-bf06-485f-968b-11a018db42ba)

## Description:
As seen from images attached above, when adding a non-empty preamble to complex commands that require `-pa` or `-sp`. It returns a wrong error message to the user even though `-pa` or `-sp` is present.

## Expected Output:
Should notify user with `Invalid command format` error message along with command usage of the instruction.

**Comment by alvinlim277** [comment]
In order to provide a command specific error message, we would essentially be parsing the user's incorrect input correctly in order to tell them that their input is incorrect (if that makes sense).

Using this example, we would parse out _"list"_ from the input to know in the first place that the user was trying to input a `ListCommand`. Then, we would have to detect _"-pa"_ to know the user has a valid `personType` in their input. At this point we have all the necessary information to execute the command, but instead we want to tell the user to change their input...

A quick fix to this behaviour would be to have _"list randomword"_ (i.e. anything before the `personType` tag) be parsed as the `commandWord`, so the error message would be "Unknown command"  instead (not specific to `list`), but that itself might open a whole new can of worms.

Interested to hear the others' thoughts on this also!

**Comment by vansh284** [comment]
> In order to provide a command specific error message, we would essentially be parsing the user's incorrect input correctly in order to tell them that their input is incorrect (if that makes sense).
> 
> Using this example, we would parse out _"list"_ from the input to know in the first place that the user was trying to input a `ListCommand`. Then, we would have to detect _"-pa"_ to know the user has a valid `personType` in their input. At this point we have all the necessary information to execute the command, but instead we want to tell the user to change their input...
> 
> A quick fix to this behaviour would be to have _"list randomword"_ (i.e. anything before the `personType` tag) be parsed as the `commandWord`, so the error message would be "Unknown command" instead (not specific to `list`), but that itself might open a whole new can of worms.
> 
> Interested to hear the others' thoughts on this also!

Hm, yeah I've thought about it as well and it seems that improving the error message here would be difficult. I think we can somehow be happy with the current behaviour as long as we are convinced that the error message is not "incorrect", but just could be "better".

`list randomword` should also not be "unknown command" since `list` itself is a somewhat known command.

It could be argued that we specified the command format as `list -PERSON_TYPE` so this case truly is a case of an incorrect person type. Our `-PERSON_TYPE` is meant to come right after `list`.
