### ISSUE TITLE
Inconsistent error message for view command

### ISSUE THREAD

**Issue by Gavino3o** [AY2324S1-CS2103T-W13-1/tp#176]
![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/95404279/a8fc1eff-59d5-4e8b-8a7a-260e1e956dcc)

![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/95404279/a135ffc0-e476-4e9d-9e12-41765c4d587f)

![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/95404279/1e39ac15-6543-4915-9ff2-0252e02f7041)

## Description:
When entering the `view` command with index 0 or negative indexes. It does not show a useful error message akin to when the index larger than the size of the list.

## Expected:
For all scenarios above, a useful error message should be shown. Preferably, the message in the third attached image with better description (can refer to `delete` command.

**Comment by vansh284** [comment]
I think this is okay (the `delete` command has similar behavior btw).

Reason: 
`view 0` and `view -1` is an incorrect command format in general because it is not a positive integer, and this can never be correct.
 
`view 1000` is an invalid index for this particular list, but could be valid for some other list.

Could be argued both ways, but I don't think the error messages here are incorrect (i.e. we don't need to fix for v1.4)

**Comment by Gavino3o** [comment]
Thank you for the clarification. I will be closing this issue for now to be potentially reopened and worked on in the future.
